steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - services/webhook_receiver/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/ouroboros-507503/ouroboros/webhook-receiver:latest
      - .
images:
  - us-central1-docker.pkg.dev/ouroboros-507503/ouroboros/webhook-receiver:latest
