"""initial schema

Revision ID: ad8c36557236
Revises:
Create Date: 2026-09-03 12:57:49.299298

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Text(), nullable=True),
        sa.Column("claim_id", sa.Text(), nullable=True),
        sa.Column("api", sa.Text(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("units", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cost_events_project_at", "cost_events", ["project_id", "at"], unique=False)
    op.create_table(
        "prior_decisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("studio_id", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("entity_normalized", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_prior_decisions_studio_entity",
        "prior_decisions",
        ["studio_id", "entity_normalized"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("studio_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column(
            "shooting_countries", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "distribution_territories",
            postgresql.ARRAY(sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("budget_cap_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "risk_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("evidence_id", sa.Text(), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("cost_band", sa.Text(), nullable=True),
        sa.Column("remediation_suggested", sa.Boolean(), nullable=False),
        sa.Column("remediation_kind", sa.Text(), nullable=True),
        sa.Column("territory_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("gcs_uri", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind in ('script','cut')", name="assets_kind_check"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
    )
    op.create_table(
        "claims",
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("studio_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("entity_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("jurisdictions", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    op.create_index(
        "ix_claims_project_category", "claims", ["project_id", "category"], unique=False
    )
    op.create_index("ix_claims_project_status", "claims", ["project_id", "status"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.Text(), nullable=False),
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("parallel_run_id", sa.Text(), nullable=True),
        sa.Column("previous_interaction_id", sa.Text(), nullable=True),
        sa.Column("processor", sa.Text(), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overall_confidence", sa.Text(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index("ix_evidence_claim_cycle", "evidence", ["claim_id", "cycle"], unique=False)
    op.create_table(
        "monitors",
        sa.Column("monitor_id", sa.Text(), nullable=False),
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("task_run_id", sa.Text(), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("frequency", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
        ),
        sa.PrimaryKeyConstraint("monitor_id"),
    )
    op.create_table(
        "verification_history",
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_verification_history_claim_at", "verification_history", ["claim_id", "at"], unique=False
    )
    op.create_table(
        "risk",
        sa.Column("claim_id", sa.Text(), nullable=False),
        sa.Column("evidence_id", sa.Text(), nullable=False),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("cost_band", sa.Text(), nullable=True),
        sa.Column("remediation_suggested", sa.Boolean(), nullable=False),
        sa.Column("remediation_kind", sa.Text(), nullable=True),
        sa.Column("territory_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claim_id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.evidence_id"],
        ),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk")
    op.drop_index("ix_verification_history_claim_at", table_name="verification_history")
    op.drop_table("verification_history")
    op.drop_table("monitors")
    op.drop_index("ix_evidence_claim_cycle", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_claims_project_status", table_name="claims")
    op.drop_index("ix_claims_project_category", table_name="claims")
    op.drop_table("claims")
    op.drop_table("assets")
    op.drop_table("risk_history")
    op.drop_table("projects")
    op.drop_index("ix_prior_decisions_studio_entity", table_name="prior_decisions")
    op.drop_table("prior_decisions")
    op.drop_index("ix_cost_events_project_at", table_name="cost_events")
    op.drop_table("cost_events")
    # ### end Alembic commands ###
